language: haskell

env:
  - GHCVER=7.6.3
  - GHCVER=7.8.4
  - GHCVER=7.10.1

before_install:
  - |
      # Install the GHC we want from hvr's PPA
      travis_retry sudo add-apt-repository -y ppa:hvr/ghc
      travis_retry sudo apt-get update
      travis_retry sudo apt-get install cabal-install-1.22 ghc-$GHCVER happy
      export CABAL=cabal-1.22
      export PATH=/opt/ghc/$GHCVER/bin:$PATH

  - $CABAL update

  # Update happy when building with GHC head
  - |
    if [ $GHCVER = "7.8.4" ] || [ $GHCVER = "7.10.1" ]; then
      $CABAL install --constraint=transformers\ installed happy alex
      export PATH=$HOME/.cabal/bin:$PATH
    fi

install:
  - $CABAL sandbox init
  - cd katip
  - ln -s ../.cabal.sandbox.config .
  - $CABAL install --dependencies-only --enable-tests --enable-benchmarks
  - $CABAL configure --enable-tests --enable-benchmarks -flib-Werror
  - $CABAL install
  - cd ../katip-elasticsearch
  - ln -s ../.cabal.sandbox.config .
  - cd ..

script:
  - cd katip
  - $CABAL build
  - $CABAL test --show-details=always
  - $CABAL bench
  # tests that a source-distribution can be generated
  - $CABAL sdist

  - cd ../katip-elasticsearch
  - $CABAL build
  - $CABAL test --show-details=always
  - $CABAL bench
  - $CABAL sdist
